# docker-compose のフォーマットバージョン
version: '3.7'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    # volumes:
    #   - "./data/redis:/data"
    
    # Docker Engine(Desktop)起動時にコンテナが自動起動する設定
    restart: always
    